### PR TITLE
Fixes/Added functionality

### PR DESCRIPTION
**Pull request by JoriPS1**
New/Set licenses
Removed Validate Length from New-SnipeitLicense -license_email, bringing it in line with Set. This was causing the parameter to fail as it cannot validate the mailaddress object.
Added code to convert -license_email to string, as required by the SnipeitAPI.
Added -purchase_order functionality.

New Supplier
Fixed typo in API which was causing the command to fail.

### CODE REVIEW

**Comment by PetriAsi** [comment]
Thanks, your pull request is now against develop and using correct branches.

One thing more. Git can be tricky. Your pull request shows lots of commits that are made by others than you.
Could you please [rebase](https://git-scm.com/docs/git-rebase) you PR against current develop. that cleans those unneeded commits from change logs.

Then  at your local repo/featurebranch , add new remote git@github.com:snazy2000/SnipeitPS.git as upstream. (by running git add remote ... and  git fetch )

Then from git terminal run:

```
 git rebase upstream/develop -i

```
git will open commit log on text editor, **edit  file and left only lines with your own commits on file**
save and close, commit and push to github
 you feature branch

No need for new pr as changes will show up here.
After this is ready to merge.

**Comment by JoriPS1** [comment]
This was my first pull request (and time using git).  I guess I just don't understand why there are these hoops to jump through. The rebase documentation is just wall of text that I can't make any sense of it.

**Comment by PetriAsi** [comment]
I have been there too, it was really frustrating trying learn it. Still not mastering it, but find one way to do it. 

As I wrote before, on your local clone, add new remote repo, fetch it, and then from git bash run interactive rebase.

Then push changes to your github branch.

Let force be with you

**Comment by PetriAsi** [comment]
Rebased this and made new PR #295

**Pull request closed without merging**
