### PR TITLE
Add additional parameters and help to Get functions

### PR DESCRIPTION
**Pull request by mattcarras**
Add additional parameters and missing help to Get functions. Mostly searching by name wherever possible. Also adds searching by custom fields for assets.

### CODE REVIEW

**Comment by PetriAsi** [comment]
Great, nice work, thank you. We always need more documentation and features to keep up with API.
After revieving you PR I find two things that need change. First, source branch should now be master branch. add new branch your repo and make pull request against it. (you can edit this pr and change source branch or create new one)
And second just visual thing, recheck code formatting, that everything follows existing formatting. For example the parameters 
should use constant formatting.
After those changes I'm more than happy to merge your contbutions.

**Comment by mattcarras** [comment]
> Great, nice work, thank you. We always need more documentation and features to keep up with API. After revieving you PR I find two things that need change. First, source branch should now be master branch. add new branch your repo and make pull request against it. (you can edit this pr and change source branch or create new one) And second just visual thing, recheck code formatting, that everything follows existing formatting. For example the parameters should use constant formatting. After those changes I'm more than happy to merge your contbutions.

And thank you for all the hard work you've done on SnipeitPS! Sorry it took me so long to respond. I totally missed the formatting problem, and missed one additional parameter for Get-SnipeItAsset.

As for the fork, I thought I originally forked [snazy2000:master](https://github.com/snazy2000/SnipeitPS)? That's what it shows on my end, so I'm a bit confused.

**Comment by PetriAsi** [comment]
Yep, branches can be little confusing first.

It's ok to fork master, it's latest release.  Although I'll merge everything to develop branch here and from there to release it to master. Every  commit to master is automatically  released to ps gallery.

So what I like you to do, is create local feature branch from your local master. push it to you github  repo and edit this PR.

So on your local repo run something like: 
```bash
#create feature branch named  'new-feature' from you local master 
git checkout -b new-feature

#push feature branch to you github repo 
git push -u origin new-feature
```

Then edit this PR , And use  develop-branch and your feature branch as target and source.
By using feature branches we get more meaningful commit names and things keep tidy.

**Comment by mattcarras** [comment]
Ended up making new pr #281. Closing this one.

**Pull request closed without merging**
