### PR TITLE
Revert "Get everything by id"

### PR DESCRIPTION
**Pull request by snazy2000**
Reverts snazy2000/SnipeitPS#75

### CODE REVIEW

**Comment by PetriAsi** [comment]
What kind of issues did "Get everything by id" had? I have used it in production whole time?

**Comment by snazy2000** [comment]
I merged to wrong branch by mistake will try spend some time getting all these merged in

**Comment by PetriAsi** [comment]
Yep, it will take time. And my "cumulative" pull requests are not making it any easier.

**Comment by PetriAsi** [comment]
@snazy2000 is it ok to merge this to develop?

**Pull request merged**
