### PR TITLE
Add Next Audit Date to New-SnipeItAudit.ps1

### PR DESCRIPTION
**Pull request by RussellLeVasseur**
Added values to set next audit date per https://snipe-it.readme.io/reference/hardwareaudit params.

### CODE REVIEW

**Comment by RussellLeVasseur** [comment]
probably need a way to sanitize the date format. I need to also put instructions for the date at the top. Let me add that real quick.

**Comment by RussellLeVasseur** [comment]
@PetriAsi, @snazy2000
Happy Monday! Was wondering if this could get a look and get merged, please!

**Comment by PetriAsi** [comment]
Thanks! Looking good.  
I was just wondering if this parameter should be called "next_audit_date" as it is in API? That way SnipeitPS  parameters will always be same as in API.

**Comment by RussellLeVasseur** [comment]
I originally had it as that, but tried to kinda match existing naming. I'm all for next_audit_date though

**Comment by PetriAsi** [comment]
Great! And also retarget this PR to develop branch here.

**Comment by PetriAsi** [comment]
Looking good, but  I just  noticed just now that there's lots of other people commits included.  Git can be tricky some times . I have done  same kind of  commit clean up for my PRs by rebasing my forked branch against upstream.

So, could you please do rebasing against upstream/develop by running 
```
git rebase -i upstream/develop
```
Then left only your own commits to your branch and this PR. Cleaning PR history  will keep  git commit logs usefull for everyone.

If you don't have upstream in you local repo just add it by
```
git remote add upstream https://github.com/snazy2000/SnipeitPS.git
git pull upstream
```

**Comment by RussellLeVasseur** [comment]
> Looking good, but I just noticed just now that there's lots of other people commits included. Git can be tricky some times . I have done same kind of commit clean up for my PRs by rebasing my forked branch against upstream.
> 
> So, could you please do rebasing against upstream/develop by running
> 
> ```
> git rebase -i upstream/develop
> ```
> 
> Then left only your own commits to your branch and this PR. Cleaning PR history will keep git commit logs usefull for everyone.
> 
> If you don't have upstream in you local repo just add it by
> 
> ```
> git remote add upstream https://github.com/snazy2000/SnipeitPS.git
> git pull upstream
> ```

Is there a way to do this with the Web GUI? I am not using git CLI.

**Comment by PetriAsi** [comment]
It seems that that web gui does not support rebasing. #isaacs/github#88
I'm using plain git for windows or plain git with linux and macos . 
It's quite easy to setup, just go ahead and try.  Creating ssh-keys could feel tricky for
the first time, but after that is done it's nice to use.

I just tested  made local copy of your fork.  And added upstream. I can made new PR  from my repo if you
dont have time clean your request. Commits are still authored by you.
 But I hope that you do install git client , then you can  have you local git repo for dev and testing. Pushing to github is only when there's need to publish something or make new PR for SnipeitPS.

**Comment by PetriAsi** [comment]
it seems that you missed one $next_audit  when changing that to $next_audit_date

**Comment by PetriAsi** [comment]
@RussellLeVasseur . I'll close this and merge your changes from cleaned up branch. Thanks for this change.

**Pull request closed without merging**
